# This script calculates partition coefficient from the _Background_stat.csv and _droplet_stats.csv file generated by the "Partition_Coefficient_Macro_Image_Stat.ijm" ImageJ macro.

import os
folder_list = [x for x in os.listdir() if '.' not in x] 
# Partition data for y protein into x protein condensate is saved in 'x\y' folder. 
# That is partition of y1 is saved in x/y1, y2 is saved in x/y2 folder and so on.
# folder_list is essentially a list of all proteins that are partitioned into x protein condensates.

base_folder = os.getcwd()

# Read droplet data and background data. Calculate partition coefficient (with error propagation). 
import pandas as pd
def fetch_data_from_a_folder(recruited_protein):
    import pandas as pd
    os.chdir(recruited_protein)
    try:
        df_pc = pd.read_csv('Partition_Coefficient_Data.csv', index_col=0)
        df_pc['recruited_protein'] = recruited_protein
    except:
        df_pc = pd.DataFrame()
    os.chdir(base_folder)
    return df_pc
final_df = pd.concat([fetch_data_from_a_folder(x) for x in folder_list], ignore_index=True)

# Plot partition coefficient data for x protein condensates. 
from matplotlib import pyplot
import seaborn as sns

a4_dims_portrait = (11.7, 8.27)
a4_dims_landscape = (8.27, 11.7)
fig, ax = pyplot.subplots(figsize=(16,8))
sns.set_context("paper", rc={"font.size":8,"axes.titlesize":8,"axes.labelsize":5})  
ax = sns.boxplot(x="recruited_protein", y="Partition_Coefficient", data=final_df)
ax = sns.swarmplot(x=final_df["recruited_protein"], y=final_df["Partition_Coefficient"], 
                   color="black"
                   , edgecolor="gray",
                   size=4,
                   **{'alpha':.6}
                  )

pyplot.tick_params(axis='both', which='major', labelsize=18)
pyplot.xlabel('Partitioned Protein', fontsize= 20)
pyplot.ylabel('Partition Coefficient', fontsize=20)
pyplot.title(f'{condensate_forming_protein} condensate', fontsize = 24)
pyplot.savefig(f'{condensate_forming_protein} plot.pdf')